### PR TITLE
Allow to specify preview ref #4

### PR DESCRIPTION
**Pull request by mitevs-mms**
This will allow for providing custom prismic ref as a header when executing graphql queries

### CODE REVIEW

**Comment by Corjen** [comment]
@mitevs-mms, could you maybe provide an example of how this works?

**Comment by mitevs-mms** [comment]
@Corjen Yes

1. Create ApolloClient, using the PrismicLink:
  
```js
const link = PrismicLink({ URI_TO_YOUR_PRISMIC })

const client = new ApolloClient({
  link,
  ...
})
```

2. Execute your query and pass the header as part of the CTX 

```js
client.query({
  query: ...,
  variables: ...,
  context: {
    headers: {
      'Prismic-Ref': 'YOUR PRISMIC REF'
    }
  }
})
```

Now, it's up to you how you load the prismic ref. In our project we have koa route /preview that we have configured in prismic that will give us the ref of any unpublished changes, which we then get from the QS that prismic created when redirecting to our /preview route. Then we pass this QS param (the prismic ref) to our query as options, which in turn is passed to the prismic (code above). 

The actual PR I created only rearranges the order of destructing the headers in the setContext. This allows for custom ref because now the headers are destructed after the default master ref header is set. So, in case you pass one, you will overwrite the default ref set by the prismic link.

I hope this helps,
Cheers!

**Comment by Corjen** [comment]
@mitevs-mms thanks for taking the time! Really appreciate it!

**Comment by mitevs-mms** [comment]
@Corjen Hey np, hope it helps ;)

**Comment by igorlesnenko** [comment]
Would it be better to pass previewRef when we creating a link?

```
const link = new PrismicLink({
      uri,
      previewRef
    });
```

e.g. we use it for stitching

**Comment by mitevs-mms** [comment]
@igorlesnenko not sure what is the use-case you have, but for us creating the /preview route this cannot work because we don't know the previewRef ahead of time and we can only get it through the /preview route redirect from prismic. If you need to do a preview feature in your app, then you cannot do it like this because the ref comes as a query param to you, and that is the CTX from your server then has to be passed as a CTX to the query (GraphQLContext), which comes with each query execution.

I hope this helps.

Cheers!

**Comment by igorlesnenko** [comment]
@mitevs-mms I store previewRef in a cookie when preview route is triggered. So now I can use it in apollo-link like: 

```
const previewCookie = 'io.prismic.preview';
const previewRef = request.cookies[previewCookie];
const link = new PrismicLink({
      uri,
      previewRef
    });
```

**Comment by mitevs-mms** [comment]
I think this is not too obvious. The Link accepts context, and as part of the context you can pass headers. This is much more clear to me. But, if you wish to do this, probably you will have to create PR and ask for approval. In this case the context doesn't make sense, what do you think?

**Pull request merged**
